### ISSUE TITLE
Add fake news data

### ISSUE THREAD

**Issue by mdogucu** [mdogucu/bayesrules#12]

**Comment by mdogucu** [comment]
Alicia, @ajohns24 , would you please direct me to the source of this dataset please? I do not need a clean version, I just need the link to wherever the data was downloaded from. Thank you!!

**Comment by mdogucu** [comment]
@ajohns24 Just saw this in text!!! Feeling stupid.

**Comment by ajohns24** [comment]
@mdogucu sorry I'm just seeing this!  Glad you found what you needed.  I'll look more carefully at notifications in the future :)
