### ISSUE TITLE
plot_normal parameter

### ISSUE THREAD

**Issue by MilesOtt** [mdogucu/bayesrules#54]
make an argument for what parameter should be used in the plot (right now it is theta, but I would like the option to plot with mu for Chapter 5)

**Comment by mdogucu** [comment]
We used to parametrize the normal with theta in the past. Should we just
change to mu rather than adding an argument?

**Comment by MilesOtt** [comment]
For the normal-normal conjugate chapter it is helpful to be able to plot mu~N(theta, tau) and X~N(mu, sigma)

**Comment by mdogucu** [comment]
Makes sense!
