### ISSUE TITLE
basketball

### ISSUE THREAD

**Issue by mdogucu** [mdogucu/bayesrules#73]
If to be used `basketball` needs to be cleaned up.

If not to be used then `basketball` needs to be removed.

**Comment by MilesOtt** [comment]
I'm looking at chapter 18 and we could do something in the exercises with these data where the grouping variable is team, and we use age to predict the number of games a player plays in a season first with a normal model, then with Poisson model, then with Negative Binomial

**Comment by mdogucu** [comment]
If you have any interest and the time feel free to try it. Per game statistics glossary is [here](https://www.basketball-reference.com/wnba/players/a/abdifa01w.html) and has not yet been documented.

**Comment by MilesOtt** [comment]
hi @mdogucu I want to change some things about the basketball data itself now that I have the documentation up, but I'm not sure how to do that and I don't want to mess anything up. When you get a chance could I chat with you for 5 minutes? No rush at all.

**Comment by mdogucu** [comment]
hi @MilesOtt. I am "free" after 12 pm PT. We can meet and walk through the data if you would like.

**Comment by MilesOtt** [comment]
Sweet that would be awesome! Thank you! I just sent you an invite.

**Comment by mdogucu** [comment]
@ajohns24 will add total minutes
